export const ROUTES = {
  panelDashboard: '/panel/dashboard',
  panelWalletMyWallet: '/panel/wallet/my-wallet',
  panelWalletTomanDeposit: '/panel/wallet/toman-deposit',
  panelWalletIdDeposit: '/panel/wallet/id-deposit',
  panelWalletCryptoDeposit: '/panel/wallet/crypto-deposit',
  panelWalletTransactionsList: '/panel/wallet/transactions-list',
  panelWalletTomanWithdraw: '/panel/wallet/toman-withdraw',
  panelWalletCryptoWithdraw: '/panel/wallet/crypto-withdraw',
  panelUserBankAccounts: '/panel/wallet/bank-accounts',
  panelMyAccountRefferals: '/panel/referrals',
  panelInstantTradeBuy: '/panel/instant-trade/buy',
  panelInstantTradeSell: '/panel/instant-trade/sell',
  panelInstantTradeConvert: '/panel/instant-trade/convert',
  panelInstantMarket: '/panel/instant-market',
  panelAdvanceMarket: '/panel/advance-market',
  panelAdvancedTrade: '/panel/advance-trade',
  panelOpenOrders: '/panel/open-orders',
  panelMyAccountProfile: '/panel/my-account/profile',
  panelMyAccountSecurity: '/panel/my-account/security',
  panelMyAccountConvert: '/panel/my-account/convert',
  panelMyAccountMessages: '/panel/my-account/messages',
  panelMyAccountNotifications: '/panel/my-account/messages',
  panelMyAccountValidation: '/panel/my-account/validation',
  panelMyAccountSettings: '/panel/my-account/settings',
  panelReferral: '/panel/referrals',
  panelSupport: '/panel/support',
  panelSupportTickets: '/panel/support/tickets',
  panelSupportNewTicket: '/panel/support/new-ticket',
  panelGiftCard: '/panel/gift_card',
  panelCommission: '/panel/my-account/commission',
  help: (section: string) => `/help/${section}`,
};
